title: colrev-workshop
description: The CoLRev workshop page
theme: just-the-docs

url: https://digital-work-lab.github.io/handbook

repository: CoLRev-Environment/workshop

gh_edit_link: true
gh_edit_link_text: 'Edit this page on GitHub'
gh_edit_repository: 'https://github.com/CoLRev-Environment/workshop'
gh_edit_branch: 'main'
gh_edit_view_mode: 'tree'

search:
    focus_shortcut_key: 'k'

mermaid:
  version: "9.1.3"

plugins:
  - "jekyll-github-metadata"

enable_copy_code_button: true

# logo: "/assets/images/digital-work-lab.png"

callouts:
  warning:
    title: Warning
    color: red
  highlight:
    title: Info
    color: yellow
